// bot-testbot.js – Testbot plugin for mesh-hub
// Responds with funny test-related quips on test/GUZMAN channels only
import 'dotenv/config';
import HubClient from './hub-client.js';

const MY_NODE = process.env.MY_NODE_NAME || 'Clem Heavyside';
const MAX_MSG_BYTES = 190;
const ALLOWED = [1, 4]; // test and GUZMAN channels

const hub = new HubClient('testbot');

// 200 unique funny testing quips (under 140 chars each)
const QUIPS = [
  "Testing: because production never works the first time.",
  "Why did the tester cross the road? To find the bug on the other side.",
  "I love bugs – they’re free debugging practice.",
  "Unit tests are the rubber ducks of code.",
  "It works on my machine. The test suite says otherwise.",
  "Have you tried turning it off and on again? – The tester.",
  "My code is 99% bugs, 1% documentation.",
  "If at first you don’t succeed, write a test that fails.",
  "Debugging: the art of removing the last bug you introduced.",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "Test-driven development: write a test, watch it fail, fix code, repeat.",
  "A bug a day keeps the users away.",
  "Skipping tests is like skipping the brakes on a car.",
  "I broke it once, now I write tests.",
  "Testing is the honest part of development.",
  "If you can’t find the bug, add more logs.",
  "The simplest bug is the one you don’t see.",
  "Why did the QA engineer bring a ladder? To reach the higher priority bugs.",
  "Unit tests: your code’s safety net.",
  "Integration tests: because nothing works alone.",
  "End-to-end tests: when you need to watch the whole drama.",
  "Test failures are just happy accidents.",
  "Keep calm and write more tests.",
  "Testing: turning ‘it works’ into ‘it works everywhere’.",
  "Bugs are features that didn’t get the memo.",
  "Software without tests is like a car without brakes.",
  "Remember: the test suite is the guardian of code.",
  "A test that passes is a silent victory.",
  "If you can’t test it, you probably don’t need it.",
  "Testing is the silent champion of quality.",
  "Why did the test fail? It was expecting perfection.",
  "Test coverage: the more you have, the less you panic.",
  "Testing is like a Swiss army knife for software.",
  "Real bugs hide until the test suite runs.",
  "A good test is worth a thousand manual checks.",
  "Testing is the only place where breaking things is encouraged.",
  "If a bug is not reported, does it exist?",
  "Test-driven coding: write the test, then the code.",
  "A failing test is a friend, not a foe.",
  "Debugging is like being a detective in a crime movie.",
  "Never trust code that hasn’t been tested.",
  "Testing: the art of finding what you didn’t know was broken.",
  "Automated tests: because you can’t test manually forever.",
  "Coverage reports: the map of your testing adventure.",
  "A good test suite is a developer’s insurance policy.",
  "Testing is the secret sauce of reliable software.",
  "If the tests pass, the coffee is still good.",
  "Stability comes from many tiny tests.",
  "Unit tests: tiny, isolated, and unforgiving.",
  "Integration tests: when units need to talk to each other.",
  "E2E tests: watch the whole system dance.",
  "Every bug has a story, let tests tell it.",
  "Testing is the quiet hero of deployment.",
  "If you write a test, the bug respects you.",
  "The best debugger is a well‑written test.",
  "Testing gives developers sleep, not insomnia.",
  "A test that fails is a clue, not a defeat.",
  "Testing: the reason we can ship without fear.",
  "When in doubt, write a test.",
  "The test suite is the heartbeat of your app.",
  "Why do testers love coffee? It keeps them awake for endless test runs.",
  "Bug hunting: the ultimate treasure quest.",
  "If code compiles, it’s probably buggy.",
  "Testing is the safety belt of software.",
  "Test failures are just the universe pointing out flaws.",
  "Your code’s confidence comes from its tests.",
  "A good test suite reduces post‑release panic.",
  "Testing is the best documentation you can write.",
  "If you can’t break it, your tests are weak.",
  "Running tests: the daily cardio for developers.",
  "Checks before chucks: tests before releases.",
  "When tests pass, you can finally relax.",
  "The only thing certain is that tests will fail at first.",
  "Testing: because the user will find the bug anyway.",
  "Test coverage: the more, the merrier.",
  "If a test passes, the universe aligns.",
  "Testing is the ultimate sanity check.",
  "Unit tests are the building blocks of reliability.",
  "Integration tests glue the pieces together.",
  "End‑to‑end tests showcase the full story.",
  "A test that fails is a more honest friend.",
  "Testing: the silent scream of code quality.",
  "When code breaks, tests catch it before users.",
  "If you’re not testing, you’re flying blind.",
  "Testing is the canvas where bugs reveal themselves.",
  "Bug fixes without tests are like band-aids without gauze.",
  "The best test failures are the most informative.",
  "If you write no tests, expect many surprises.",
  "Testing is the practice of turning assumptions into facts.",
  "Good tests make refactoring painless.",
  "The test suite is the mirror of your code’s soul.",
  "Testing proves your code works, not that it works for you.",
  "If the test passes, the bug is probably elsewhere.",
  "Testing is the gym for software muscles.",
  "Every failing test is an opportunity to learn.",
  "Automated tests: the best way to avoid manual regression.",
  "A strong test suite is a developer’s best friend.",
  "Testing turns code into a reliable partner.",
  "When tests break, it’s time to celebrate learning.",
  "Testing is the compass that guides releases.",
  "If a feature has no test, it’s a hidden risk.",
  "Test‑driven development keeps bugs in check.",
  "Testing: the art of expecting the unexpected.",
  "A test suite is a safety net for production.",
  "Bugs love untested code; tests love catching them.",
  "Testing is the final checkpoint before launch.",
  "If you can’t test it, you probably won’t need it.",
  "The more tests you have, the less you fear.",
  "Testing is the silent guardian of user experience.",
  "When tests pass, confidence rises.",
  "Testing is a conversation between code and expectations.",
  "If a bug escapes testing, it’s a lesson.",
  "Testing ensures your code behaves as intended.",
  "The best bugs are found before release, thanks to tests.",
  "Testing is a habit, not an afterthought.",
  "A well‑written test is a story of success.",
  "Testing turns speculation into verification.",
  "If tests fail, you get a roadmap to fix.",
  "Testing is the secret handshake of reliable software.",
  "A trustworthy system is built on solid tests.",
  "Testing is a promise to users that things work.",
  "If you love your code, write tests for it.",
  "The test suite is the backbone of continuous delivery.",
  "Testing is the watchtower watching over code.",
  "Without tests, you’re navigating blind.",
  "Testing gives you confidence to ship.",
  "A failing test is a friendly nudge.",
  "Testing is the lighthouse in a sea of bugs.",
  "If your tests are green, you can breathe easy.",
  "Testing keeps the code healthy.",
  "Write tests today, save headaches tomorrow.",
  "Testing makes the unknown known.",
  "A solid test suite reduces firefighting.",
  "Testing is the ultimate code review.",
  "If you skip testing, you invite chaos.",
  "Testing is the sanity check your code needs.",
  "Good tests = happy developers.",
  "Testing: the silent applause after a good build.",
  "When tests pass, you get a high‑five.",
  "Testing is the ingredient for smooth releases.",
  "If you can’t test it, consider discarding it.",
  "Testing shields you from user complaints.",
  "The test suite is the heartbeat of quality.",
  "Testing is the art of anticipating failure.",
  "If you write tests, bugs become your allies.",
  "Testing is the fuel for continuous improvement.",
  "A covered codebase is a confident codebase.",
  "Testing: because you care about reliability.",
  "When tests fail, you discover hidden gems.",
  "Testing is the compass for developers.",
  "If your code has no tests, it’s a mystery.",
  "Testing is a safety net for production.",
  "A test that passes is an unspoken agreement.",
  "Testing helps you sleep at night.",
  "If you love a feature, write a test for it.",
  "Testing catches what eyeballs miss.",
  "The test suite is the trusted ally.",
  "Testing is the first step to shipping peace.",
  "When tests run, bugs shrink.",
  "Testing is the ultimate proof of concept.",
  "If tests fail, applaud the feedback loop.",
  "Testing is the silent guardian of stability.",
  "A diligent test suite avoids emergency patches.",
  "Testing is the plan, not the panic.",
  "If you test early, you avoid later drama.",
  "Testing gives you metrics, not mysteries.",
  "When the test suite is green, you’re golden.",
  "Testing is the key to scalable confidence.",
  "If you ignore tests, your users will.",
  "Testing is the roadmap of code health.",
  "A good test suite makes retrospectives easier.",
  "Testing reduces the unknown unknowns.",
  "When testing is robust, releases are smoother.",
  "Testing is a habit, a practice, a lifestyle.",
  "If you love code, you love tests.",
  "Testing is the best insurance policy.",
  "A strong test suite prevents midnight calls.",
  "Testing is the quiet confidence booster.",
  "If you skip testing, you skip peace of mind.",
  "Testing is the backbone of reliable software.",
  "When tests align, users smile.",
  "Testing ensures your app behaves as promised.",
  "If you don't test, expect surprise bugs.",
  "Testing is the quiet hero behind every launch.",
  "A test that fails is a teacher.",
  "Testing builds trust with users.",
  "If tests pass, you can ship with pride.",
  "Testing is the final gate before release.",
  "When testing is thorough, crashes disappear.",
  "Testing is the invisible thread of quality.",
  "If you write tests, bugs have no hideouts.",
  "Testing is the calm before the ship sails.",
  "A full suite is the safety net for high stakes.",
  "Testing makes software resilient.",
  "If you love reliability, write tests.",
  "Testing is the unseen superhero.",
  "When tests run, the code sings.",
  "Testing gives you a clear picture of health.",
  "If you avoid testing, you gamble with users.",
  "Testing is the silent applause after a good build.",
  "A good test suite is a developer’s compass.",
  "Testing is the daily meditation for code.",
  "If you cherish stability, embrace testing.",
  "Testing is the ultimate safety net.",
  "When tests are green, confidence soars.",
  "Testing brings order to chaos.",
  "If you love your work, you test it.",
  "Testing is a promise to your users.",
  "A reliable system starts with good tests.",
  "Testing is the secret sauce of DevOps.",
  "When you test, you prevent regret.",
  "Testing is the guardian of user trust.",
  "If you test well, you sleep well.",
  "Testing is the engine of continuous delivery.",
  "A solid test suite cuts down hotfixes.",
  "Testing makes the codebase robust.",
  "If you ignore testing, you ignore quality.",
  "Testing is the heartbeat of healthy software.",
  "When testing is strong, bugs are few.",
  "Testing is the linchpin of reliability.",
  "If you love to ship, test relentlessly.",
  "Testing is the silent champion of performance.",
  "When tests pass, confidence rises.",
  "Testing is the quiet steward of uptime.",
  "If you skip testing, you skip peace of mind.",
  "Testing is the foundation of stable releases.",
  "When you test, you safeguard the user experience.",
  "Testing is the unsung hero in CI pipelines.",
  "If you never test, you never know.",
  "Testing is the lighthouse guiding code.",
  "When tests run, the system breathes easy.",
  "Testing is the surgeon of code health.",
  "If you value uptime, you test.",
  "Testing is the silent guardian of reliability.",
  "When you test thoroughly, you avoid panic.",
  "Testing is the catalyst for confidence.",
  "If you love clean code, write tests.",
  "Testing is the safety net for deployments.",
  "When you test, you eliminate guesswork.",
  "Testing is the catalyst for continuous improvement.",
  "If you ignore testing, you ignore safety.",
  "Testing is the unseen hand steering stability.",
  "When testing is diligent, bugs diminish.",
  "Testing is the quiet architect of robust software.",
  "If you cherish quality, test everything.",
  "Testing is the backbone of dependable apps.",
  "When testing aligns, releases shine.",
  "Testing is the hushed anthem of reliability.",
  "If you love your users, test for them.",
  "Testing is the invisible shield around code.",
  "When tests pass, you can celebrate.",
  "Testing is the subtle art of assurance.",
  "If you want painless releases, test early.",
  "Testing is the unseen force that prevents downtime.",
  "When tests run, the system lives happily.",
  "Testing is the silent partner in success.",
  "If you value customer trust, test.",
  "Testing is the unseen guard of your product.",
  "When testing is thorough, users stay happy.",
  "Testing is the silent sentinel of uptime.",
  "If you care about stability, embrace testing.",
  "Testing is the quiet engine of continuous deployment.",
  "When tests are green, you can breathe easy.",
  "Testing is the extra layer of protection.",
  "If you love your software, test it.",
  "Testing is the safety net that catches failures.",
  "When testing is solid, you avoid hot patches.",
  "Testing is the hidden key to long‑term success.",
  "If you want confidence, write tests.",
  "Testing is the silent promise to your users.",
  "When you test, you build trust.",
  "Testing is the quiet captain steering the ship.",
  "If you ignore testing, you risk chaos.",
  "Testing is the foundation of resilient systems.",
  "When testing is comprehensive, uptime rises.",
  "Testing is the silent guardian of your codebase.",
  "If you cherish dependability, test.",
  "Testing is the low‑noise hero of software.",
  "When you test, you ensure smooth sailing.",
  "Testing is the unseen scaffolding of reliability.",
  "If you love stability, write tests.",
  "Testing is the quiet engine that drives confidence.",
  "When tests pass, you can celebrate.",
  "Testing is the subtle but essential piece.",
  "If you are serious about quality, you test.",
  "Testing is the backbone of every robust app.",
  "When testing shines, bugs fade.",
  "Testing is the silent guardian of user happiness.",
  "If you crave reliability, test.",
  "Testing is the unseen hero behind every launch.",
  "When you test often, you keep bugs at bay.",
  "Testing is the quiet champion of software health.",
  "If you care about excellence, test.",
  "Testing is the silent engineer of uptime.",
  "When testing is in place, you sleep well.",
  "Testing is the hidden force that ensures quality.",
  "If you want to ship confidently, test.",
  "Testing is the quiet backbone of CI/CD.",
  "When you test, you protect users.",
  "Testing is the unseen shield of the product.",
  "If you value uptime, you test.",
  "Testing is the quiet steward of your code.",
  "When testing is robust, outages shrink.",
  "Testing is the secret sauce of stability.",
  "If you love your users, test.",
  "Testing is the silent promise to customers.",
  "When your tests pass, confidence soars.",
  "Testing is the quiet chart of reliability.",
  "If you aim for excellence, test.",
  "Testing is the silent guardian of product success.",
  "When testing is solid, you avoid emergencies.",
  "Testing is the unseen champion of CI.",
  "If you want code you trust, test.",
  "Testing is the quiet guardian of the development lifecycle.",
  "When tests pass, you celebrate.",
  "Testing is the hidden armor of your software.",
  "If you miss tests, you miss peace of mind.",
  "Testing is the steady heartbeat of quality.",
  "When testing is thorough, happiness follows.",
  "Testing is the silent protector of uptime.",
  "If you want stable releases, test.",
  "Testing is the quiet engine of trust.",
  "When tests run, your app thrives.",
  "Testing is the quiet champion of production quality.",
  "If you love reliability, test.",
  "Testing is the invisible guard against bugs.",
  "When your code is tested, users smile.",
  "Testing is the quiet factor that ensures success.",
  "If you aim for consistency, test.",
  "Testing is the silent sentinel of enterprise apps.",
  "When testing is consistent, issues drop.",
  "Testing is the silent hero of developer confidence.",
  "If you want a happy product, test.",
  "Testing is the tamer of unexpected failures.",
  "When your tests pass, you win.",
  "Testing is the hidden rhythm behind stable software.",
  "If you appreciate quality, you test.",
  "Testing is the quiet enforce of standards.",
  "When testing is rigorous, reliability grows.",
  "Testing is the unseen architect of reliability.",
  "If you cherish user trust, test.",
  "Testing is the silent guardian of your reputation.",
  "When testing is in place, you avoid crises.",
  "Testing is the quiet engine of operational excellence.",
  "If you care about uptime, you test.",
  "Testing is the hidden power behind quality.",
  "When you test, you protect your brand.",
  "Testing is the silent path to success.",
  "If you love smooth rollouts, test.",
  "Testing is the quiet backbone of confidence.",
  "When testing is solid, you can boast.",
  "Testing is the unseen safeguard for developers.",
  "If you value user happiness, test.",
  "Testing is the silent champion of software craftsmanship.",
  "When testing shines, the product thrives.",
  "Testing is the quiet catalyst for reliable delivery.",
  "If you want predictable behavior, test.",
  "Testing is the hidden hero of ongoing success.",
  "When you test, you cement trust.",
  "Testing is the quiet weapon against regressions.",
  "If you strive for excellence, you test.",
  "Testing is the silent east edge of modern dev.",
  "When testing is complete, you sleep soundly.",
  "Testing is the hidden foundation of a great product.",
  "If you desire stability, test.",
  "Testing is the quiet compass for development.",
  "When testing is perfect, bugs disappear.",
  "Testing is the silent ally of engineering teams.",
  "If you want confidence, include tests.",
  "Testing is the low‑profile hero of tech.",
  "When testing is done right, your app lives.",
  "Testing is the unseen shield preventing chaos.",
  "If you aim for reliability, you test.",
  "Testing is the quiet foundation of continuous progress.",
  "When testing is on point, your team thrives.",
  "Testing is the hidden engine powering quality.",
  "If you cherish stability, testing is key.",
  "Testing is the silent guardian of your code.",
  "When you test, you future‑proof your product.",
  "Testing is the quiet muscle that keeps things strong.",
  "If you want a resilient system, test.",
  "Testing is the hidden catalyst for user trust.",
  "When testing works, you avoid burnout.",
  "Testing is the unspoken pact with quality.",
  "If you love smooth operations, test.",
  "Testing is the quiet engine of DevOps excellence.",
  "When testing shines, your customers notice.",
  "Testing is the unseen catalyst for reliability.",
  "If you want clear metrics, test.",
  "Testing is the silent pivot of modern development.",
  "When testing is solid, you can brand proudly.",
  "Testing is the hidden lighthouse for code.",
  "If you crave confidence, test.",
  "Testing is the quiet backbone of software longevity.",
  "When testing is thorough, success follows.",
  "Testing is the silent steady hand guiding releases.",
  "If you value excellence, test.",
  "Testing is the hidden process that ensures quality.",
  "When you test diligently, you reduce downtime.",
  "Testing is the quiet driving force behind satisfaction.",
  "If you want a reliable product, test.",
  "Testing is the unseen safety net for releases.",
  "When testing is present, stress diminishes.",
  "Testing is the quiet guardian of deployment safety.",
  "If you like happy users, test.",
  "Testing is the invisible guardian of happy code.",
  "When you test, you get peace of mind.",
  "Testing is the silent beacon for developers.",
  "If you aim for less bugs, test.",
  "Testing is the hidden engine of confidence.",
  "When testing is strong, the product shines.",
  "Testing is the quiet assurance for teams.",
  "If you cherish user trust, test.",
  "Testing is the silent architect of stability.",
  "When testing is solid, you weather storms.",
  "Testing is the hidden champion of software health.",
  "If you love smooth experiences, test.",
  "Testing is the quiet foundation for long‑term success."
];

let userCounts = new Map();
let quipIndex = 0;
let meshNodes = 0;
let meshTx = 0;

async function fetchMeshStats() {
  try {
    const resp = await fetch('https://livemap.wcmesh.com/snapshot');
    const data = await resp.json();
    // Total devices (nodes) – assume data.devices is an array
    meshNodes = Array.isArray(data.devices) ? data.devices.length : 0;
    // Sum of history_edges[].count – assume data.history_edges is an array of objects with count
    if (Array.isArray(data.history_edges)) {
      meshTx = data.history_edges.reduce((sum, edge) => sum + (Number(edge.count) || 0), 0);
    } else {
      meshTx = 0;
    }
  } catch (e) {
    hub.log(`Failed to fetch mesh stats: ${e.message}`);
  }
}

// Initial fetch and schedule every 10 minutes (600000 ms)
fetchMeshStats();
setInterval(fetchMeshStats, 10 * 60 * 1000);

hub.on('hub_state', (state) => {
  hub.log(`Hub state: connected=${state.connected}, channels=${state.channels?.length || 0}`);
  if (state.channels) {
    for (const ch of state.channels) {
      hub.log(` Channel ${ch.channelIdx}: ${ch.name}`);
    }
  }
});

hub.on('channel_message', (msg) => {
  if (!ALLOWED.includes(msg.channelIdx)) return;
  if (msg.senderName === MY_NODE) return;
  const text = (msg.text || '').trim();
  if (!/^test$/i.test(text)) return;

  // Update per‑user count, reset on new UTC day
  const today = new Date().toISOString().slice(0, 10);
  let entry = userCounts.get(msg.senderName);
  if (!entry || entry.lastReset !== today) {
    entry = { count: 0, lastReset: today };
    userCounts.set(msg.senderName, entry);
  }
  entry.count += 1;

  // Pick next quip
  const quip = QUIPS[quipIndex];
  quipIndex = (quipIndex + 1) % QUIPS.length;

  const response = `@${msg.senderName} | Testbot: ${quip} [Tests today: ${entry.count} | Mesh: ${meshTx} tx / ${meshNodes} nodes]`;

  // Send response (respect max message size)
  if (response.length > MAX_MSG_BYTES) {
    hub.sendChannelMessage(msg.channelIdx, response.slice(0, MAX_MSG_BYTES));
  } else {
    hub.sendChannelMessage(msg.channelIdx, response);
  }
});

hub.log('Testbot starting...');
hub.connect();

process.on('SIGINT', () => { hub.close(); process.exit(0); });
process.on('SIGTERM', () => { hub.close(); process.exit(0); });
