// Quote Engine v1.0 - Two-tier quote system with per-user tracking
// Tier 1: Hardcoded curated quotes (always available)
// Tier 2: ZenQuotes API background fetcher (continuous backfill)
import { readFile } from 'fs/promises';
import { join } from 'path';
import { fileURLToPath } from 'url';


const CURATED_QUOTES = [
{q:'The only way to do great work is to love what you do.',a:'Steve Jobs'},
{q:'Be the change you wish to see in the world.',a:'Gandhi'},
{q:'In the middle of difficulty lies opportunity.',a:'Einstein'},
{q:'Not all who wander are lost.',a:'Tolkien'},
{q:'The journey of a thousand miles begins with one step.',a:'Lao Tzu'},
{q:'To be or not to be, that is the question.',a:'Shakespeare'},
{q:'I think, therefore I am.',a:'Descartis'},
{q:'Knowledge is power.',a:'Francis Bacon'},
{q:'Fortune favors the bold.',a:'Virgil'},
{q:'The unexamined life is not worth living.',a:'Socrates'},
{q:'Imagination is more important than knowledge.',a:'Einstein'},
{q:'Stay hungry and stay foolish.',a:'Steve Jobs'},
{q:'That which does not kill us makes us stronger.',a:'Nietzsche'},
{q:'Simplicity is the ultimate sophistication.',a:'Da Vinci'},
{q:'The only thing we have to fear is fear itself.',a:'FDR'},
{q:'Do or do not, there is no try.',a:'Yoda'},
{q:'Live long and prosper.',a:'Spock'},
{q:'With great power comes great responsibility.',a:'Uncle Ben'},
{q:'We are what we repeatedly do.',a:'Aristotle'},
{q:'The best time to plant a tree was 20 years ago.',a:'Proverb'},
{q:'Well done is better than well said.',a:'Ben Franklin'},
{q:'Where there is love there is life.',a:'Gandhi'},
{q:'Life is what happens when youre busy making plans.',a:'Lennon'},
{q:'The mind is everything. What you think you become.',a:'Buddha'},
{q:'Strive not to be a success but to be of value.',a:'Einstein'},
{q:'The best revenge is massive success.',a:'Frank Sinatra'},
{q:'Fall seven times, stand up eight.',a:'Japanese Proverb'},
{q:'Everything you can imagine is real.',a:'Picasso'},
{q:'What we achieve inwardly will change outer reality.',a:'Plutarch'},
{q:'Happiness depends upon ourselves.',a:'Aristotle'},
{q:'Turn your wounds into wisdom.',a:'Oprah'},
{q:'Believe you can and youre halfway there.',a:'T. Roosevelt'},
{q:'Act as if what you do makes a difference. It does.',a:'W. James'},
{q:'Success is not final, failure is not fatal.',a:'Churchill'},
{q:'It always seems impossible until its done.',a:'Mandela'},
{q:'The purpose of life is a life of purpose.',a:'R.W. Emerson'},
{q:'Dream big and dare to fail.',a:'Norman Vaughan'},
{q:'What you do today can improve all your tomorrows.',a:'R. Marston'},
{q:'Quality is not an act, it is a habit.',a:'Aristotle'},
{q:'It is never too late to be what you might have been.',a:'George Eliot'},
{q:'No one can make you feel inferior without your consent.',a:'E. Roosevelt'},
{q:'The best way out is always through.',a:'Robert Frost'},
{q:'Nothing is impossible, the word itself says I m possible.',a:'A. Hepburn'},
{q:'Dont count the days, make the days count.',a:'Muhammad Ali'},
{q:'Life shrinks or expands in proportion to ones courage.',a:'Anais Nin'},
{q:'You miss 100% of the shots you dont take.',a:'Wayne Gretzky'},
{q:'The only limit to our realization is our doubts.',a:'FDR'},
{q:'A person who never made a mistake never tried anything.',a:'Einstein'},
{q:'In three words I can sum up life: it goes on.',a:'Robert Frost'},
{q:'Be yourself; everyone else is already taken.',a:'Oscar Wilde'}
];
// Load additional quotes from quotes_feed.json (generated by quotefeeder.js)
(async () => {
  try {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = join(__filename, '..');
    const feedPath = join(__dirname, 'quotes_feed.json');
    const data = await readFile(feedPath, 'utf8');
    const json = JSON.parse(data);
    let added = 0;
    json.forEach(q => {
      const key = q.q + '|' + q.a;
      if (!allKnownQuotes.has(key)) {
        allKnownQuotes.set(key, q);
        added++;
      }
    });
    console.log(`[QuoteEngine] Loaded ${added} new quote(s) from quotes_feed.json`);
  } catch (_) { /* ignore missing file */ }
})();


// Background quote buffer from API
var apiQuoteBuffer = [];
var allKnownQuotes = new Map(); // key = q+a hash, value = {q,a}
var userSeenQuotes = new Map(); // key = senderName, value = {seen: Set, lastActive: timestamp}
var fetchInProgress = false;
var lastFetchTime = 0;
var FETCH_INTERVAL = 5 * 60 * 1000; // 5 minutes
var MAX_QUOTE_LEN = 85; // max quote text length for MC messages
var USER_HISTORY_TTL = 13 * 60 * 60 * 1000; // 13 hours (buffer beyond 12h window)

// Initialize allKnownQuotes with curated quotes
CURATED_QUOTES.forEach(function(q) {
 allKnownQuotes.set(q.q + '|' + q.a, q);
});

function isAscii(str) {
 for (var i = 0; i < str.length; i++) {
 if (str.charCodeAt(i) > 127) return false;
 }
 return true;
}

function quoteKey(q) {
 return q.q + '|' + q.a;
}

// Fetch batch of quotes from ZenQuotes API in background
async function fetchApiQuotes() {
 if (fetchInProgress) return;
 fetchInProgress = true;
 try {
 var resp = await fetch('https://zenquotes.io/api/quotes');
 var ct = resp.headers.get('content-type') || '';
 if (!ct.includes('application/json') && !ct.includes('text/json')) {
 console.log('[QuoteEngine] API returned non-JSON: ' + ct);
 return;
 }
 var data = await resp.json();
 if (!Array.isArray(data)) return;
 var added = 0;
 data.forEach(function(item) {
 if (!item.q || !item.a) return;
 var txt = item.q.trim();
 var auth = item.a.trim();
 // Filter: ASCII only, reasonable length, not too short
 if (!isAscii(txt) || !isAscii(auth)) return;
 if (txt.length > MAX_QUOTE_LEN || txt.length < 10) return;
 if (auth.length > 25) return;
 var key = txt + '|' + auth;
 if (!allKnownQuotes.has(key)) {
 var entry = {q: txt, a: auth};
 allKnownQuotes.set(key, entry);
 apiQuoteBuffer.push(entry);
 added++;
 }
 });
 lastFetchTime = Date.now();
 console.log('[QuoteEngine] Fetched ' + data.length + ' quotes, added ' + added + ' new (total pool: ' + allKnownQuotes.size + ')');
 } catch (e) {
 console.log('[QuoteEngine] Fetch error: ' + e.message);
 } finally {
 fetchInProgress = false;
 }
}

// Clean up old user history
function cleanupUserHistory() {
 var now = Date.now();
 var expired = [];
 userSeenQuotes.forEach(function(data, user) {
 if (now - data.lastActive > USER_HISTORY_TTL) {
 expired.push(user);
 }
 });
 expired.forEach(function(user) { userSeenQuotes.delete(user); });
}

// Get a quote for a specific user, ensuring no repeats within 12h
function getQuoteForUser(senderName) {
 var now = Date.now();
 // Get or create user tracking
 if (!userSeenQuotes.has(senderName)) {
 userSeenQuotes.set(senderName, {seen: new Set(), lastActive: now});
 }
 var userData = userSeenQuotes.get(senderName);
 userData.lastActive = now;
 // Build candidate pool: all known quotes minus what this user has seen
 var candidates = [];
 allKnownQuotes.forEach(function(q, key) {
 if (!userData.seen.has(key)) {
 candidates.push(q);
 }
 });
 // If user has seen everything, clear their history and try again
 if (candidates.length === 0) {
 console.log('[QuoteEngine] User ' + senderName + ' exhausted all ' + allKnownQuotes.size + ' quotes, resetting');
 userData.seen.clear();
 allKnownQuotes.forEach(function(q, key) {
 candidates.push(q);
 });
 }
 // Pick random from candidates
 var idx = Math.floor(Math.random() * candidates.length);
 var picked = candidates[idx];
 userData.seen.add(quoteKey(picked));
 return picked;
}

// Start background fetcher
function startQuoteEngine() {
 // Initial fetch immediately
 fetchApiQuotes();
 // Then every 5 minutes
 setInterval(fetchApiQuotes, FETCH_INTERVAL);
 // Cleanup old user data every hour
 setInterval(cleanupUserHistory, 60 * 60 * 1000);
 console.log('[QuoteEngine] Started with ' + CURATED_QUOTES.length + ' curated quotes');
}

function getQuotePoolSize() {
 return allKnownQuotes.size;
}

function getUserSeenCount(senderName) {
 var data = userSeenQuotes.get(senderName);
 return data ? data.seen.size : 0;
}

export { getQuoteForUser, startQuoteEngine, getQuotePoolSize, getUserSeenCount, CURATED_QUOTES };
